name: Build and Package VRChat Photo Uploader

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --icon=icon.ico main.py

    - name: Install Inno Setup
      run: |
        curl -L -o isetup.exe "https://jrsoftware.org/download.php/is.exe"
        start /wait isetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART

    - name: Generate installer with Inno Setup
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" VRChatPhotoUploaderSetup.iss

    - name: Upload Setup.exe
      uses: actions/upload-artifact@v2
      with:
        name: Setup.exe
        path: Output\setup.exe