name: Build and Package VRChat Photo Uploader

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --icon=icon.ico main.py
        
    - name: Rename main.exe to VRChat Photo Uploader.exe
      run: |
        cd dist
        Rename-Item "main.exe" "VRChat Photo Uploader.exe"
        
    - name: Install Inno Setup
      run: |
        curl -L -o isetup.exe "https://jrsoftware.org/download.php/is.exe"
        Start-Process -FilePath isetup.exe -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART' -NoNewWindow -Wait

    - name: Generate installer with Inno Setup
      run: |
        Start-Process -FilePath "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -ArgumentList "VRChatPhotoUploaderSetup.iss" -NoNewWindow -Wait

    - name: Upload Setup.exe
      uses: actions/upload-artifact@v3
      with:
        name: Setup.exe
        path: Output/VRChatPhotoUploaderSetup.exe
